// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbjulfiqebfgofudlkgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBianVsZmlxZWJmZ29mdWRsa2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjk4MTIsImV4cCI6MjA2Mzk0NTgxMn0.VYLtLF6_aaay9Vi4GWbYVa_WJr5t2Oe1fJmc_zalnzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);